############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/frederick-vanbrabant-769a7517a/"
weight = 2

[[main]]
name = "AI"
url = "ai"
weight = 3

[[main]]
name = "RSS"
url = "https://frederickvanbrabant.com//index.xml"
weight = 4

[[main]]
name = "Contact"
url = "contact"
weight = 5

# footer menu

[[footer]]
name = "Home"
url = "/"
weight = 1

[[footer]]
name = "BlueSky"
url = "https://bsky.app/profile/maybefrederick.bsky.social"
weight = 2

[[footer]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/frederick-vanbrabant-769a7517a/"
weight = 3

[[footer]]
name = "Contact"
url = "contact"
weight = 4

